services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Disjfa\PwaBundle\:
        resource: './../../*'
        exclude: './../../{Entity,Migrations,Tests}'

    Disjfa\PwaBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Disjfa\PwaBundle\Controller\PwaController:
        arguments:
        - '@phpmob.settings.template_helper'

